<!--Lab 3: Name Formatting for Certificates
Functions Used: strtolower(), ucfirst()
Objective:
Standardize student names for certificate printing.
Tasks:
 Accept a full name input (e.g., &quot;hARdik vAGhANI&quot;).
 Convert the entire string to lowercase.
 Use ucfirst() on each word to capitalize properly.
 Output the formatted name: &quot;Hardik Vaghani&quot;.
Bonus: Use explode() and implode() to handle multi-word names.-->

<html>
    <head></head>
<title>User Info.</title>
<body>
<form action="Lab3.php" method="post">
        FULL NAME : <input type="text" name="nm"></br></br>
        Submit :  <input type="submit" name="submit" value="Submit"></br></br>
</form>
</body>
</html>